### ISSUE TITLE
FPS Tracking

### ISSUE THREAD

**Issue by Snayff** [Snayff/nqp2#289]
## Suggested Feature 
2 different approaches in place for time tracking and neither quite working. 

## Requirements 
- [ ] use 1 internal clock
- [ ] can track fps
- [ ] can show fps in debug in info

## Additional Context
None.
